Fix extract script

diff --git a/home/.scripts/extract b/home/.scripts/extract
--- a/home/.scripts/extract
+++ b/home/.scripts/extract
@@ -2,9 +2,10 @@
 # EXTRACT
 # from http://tldp.org/LDP/abs/html/sample-bashrc.html
 # modified by untitaker
+set -e
 
 if [ -f "$1" ] ; then
-     (case "$1" in
+     case "$1" in
          *.bz2)   bunzip2 "$1"      ;;
          *.gz)    gunzip "$1"       ;;
          *.rar)   unrar x "$1"      ;;
@@ -12,7 +13,7 @@ if [ -f "$1" ] ; then
          *.Z)     uncompress "$1"   ;;
          *.7z)    7z x "$1"         ;;
          *)       tar xfv "$1" ;; # just hope for the best
-       esac) 2>/dev/null || (echo "'$1' can't be unextracted." && exit 1)
+       esac || (echo "'$1' can't be unextracted." && exit 1)
  else
      echo "'$1' is not a valid file"
      exit 1
