Update, fixed colors

diff --git a/scripts/update_mail b/scripts/update_mail
--- a/scripts/update_mail
+++ b/scripts/update_mail
@@ -1,21 +1,1 @@
-#!/bin/bash
-# A script which spawns the offlineimap daemon and "daemonizes" w3watch
-
-www2mail() {
-    while true; do
-        echo -e "\e[0;31m Updating w3watch...\e[0m"
-        w3watch_text="$(w3watch -c)"
-        if [ "$w3watch_text" ]; then
-            echo -e "\e[0;31m Updates for w3watch!\e[0m"
-            echo -e "Subject: w3watch updates \n\n $w3watch_text" > "~/.mail/uberspace-markus/INBOX/new/w3watch_$(date +%s)"
-        else
-            echo -e "\e[0;31m No updates for w3watch\e[0m"
-        fi
-        sleep 3600
-    done
-}
-
-(www2mail; echo -e "\e[0;31m www2mail exited\e[0m") &
-(offlineimap; echo -e "\e[0;31m offlineimap exited\e[0m") &
-
-wait
+killall -s USR1 offlineimap && echo "Updating mail..." || echo "Failed to update mail."
